"""Hierarchical core assembler for multi-assembly models (P2-FULLCORE-2A).

Production-grade hierarchical assembly that creates real schema objects:

* Per-type base pin lattices (without localized inserts).
* Assembly wrapper universes + cells.
* Core-level lattice from CoreLayoutPatch.
* Transmission boundary for internal assemblies.
* Centered placement with assembly gap calculation.
* Global axial segment compilation.
* Typed result model (no raw dicts).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from openmc_agent.plan_builder.patches import (
    AssemblyCatalogPatch,
    AssemblyPinMapPatchItem,
    AssemblyTypePatchItem,
    CoordinateConvention,
    CoreLayoutPatch,
    FactsPatch,
    LocalizedInsertIntentPatchItem,
    LocalizedInsertProfilesPatch,
    PinMapPatch,
)
from openmc_agent.plan_builder.scoped_counts import (
    AssemblyTypeCountSummary,
    CoreCountAggregation,
    compute_assembly_pin_counts,
    aggregate_core_counts,
)
from openmc_agent.schemas import (
    AssemblySpec,
    CellSpec,
    CoreSpec,
    LatticeSpec,
    RegionSpec,
    SurfaceSpec,
    UniverseSpec,
)


# ---------------------------------------------------------------------------
# Typed result model
# ---------------------------------------------------------------------------


@dataclass
class HierarchicalCoreAssemblyResult:
    """Typed result from hierarchical core assembly."""

    ok: bool = True
    pin_lattices: list[LatticeSpec] = field(default_factory=list)
    derived_pin_lattices: list[LatticeSpec] = field(default_factory=list)
    assembly_specs: list[AssemblySpec] = field(default_factory=list)
    assembly_universes: list[UniverseSpec] = field(default_factory=list)
    assembly_wrapper_cells: list[CellSpec] = field(default_factory=list)
    core_lattices: list[LatticeSpec] = field(default_factory=list)
    core_spec: CoreSpec | None = None
    count_summaries: dict[str, AssemblyTypeCountSummary] = field(default_factory=dict)
    core_count_aggregation: CoreCountAggregation | None = None
    assembly_universe_ids: dict[str, str] = field(default_factory=dict)
    localized_insert_reports: list[dict[str, Any]] = field(default_factory=list)
    issues: list[dict[str, str]] = field(default_factory=list)
    summary: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Single-assembly backward compatibility
# ---------------------------------------------------------------------------


def lift_single_pin_map_to_catalog(
    pin_map: PinMapPatch,
    *,
    assembly_type_id: str = "assembly_type_1",
) -> AssemblyCatalogPatch:
    """Convert a single PinMapPatch into a single-entry AssemblyCatalogPatch."""
    pm_item = AssemblyPinMapPatchItem(
        lattice_size=pin_map.lattice_size,
        default_universe_id=pin_map.default_universe_id,
        coordinate_convention=pin_map.coordinate_convention,
        guide_tube_coords=list(pin_map.guide_tube_coords),
        instrument_tube_coords=list(pin_map.instrument_tube_coords),
        water_cell_coords=list(pin_map.water_cell_coords),
        localized_insert_intents=list(pin_map.localized_insert_intents),
        assumptions=list(pin_map.assumptions),
        source_note=pin_map.source_note,
    )
    atype = AssemblyTypePatchItem(
        assembly_type_id=assembly_type_id,
        name="auto-lifted from single pin_map",
        role="single_assembly",
        pin_map=pm_item,
    )
    return AssemblyCatalogPatch(
        assembly_types=[atype],
        assumptions=["auto_lifted_from_single_pin_map"],
        source_note="Generated by lift_single_pin_map_to_catalog",
    )


# ---------------------------------------------------------------------------
# Per-type pin lattice construction (NO localized inserts in base)
# ---------------------------------------------------------------------------


def _expand_assembly_pin_map(
    pm: AssemblyPinMapPatchItem,
    kind_to_universe: dict[str, str] | None = None,
) -> list[list[str]]:
    """Expand a sparse assembly pin map into a full base universe_pattern.

    P2-FULLCORE-2A: Localized inserts (Pyrex, thimble plugs, RCCA, absorbers)
    are NOT baked into the base lattice.  They are applied as axial lattice
    loadings during the global axial segment compilation.
    """
    nx, ny = pm.lattice_size
    grid = [[pm.default_universe_id for _ in range(ny)] for _ in range(nx)]

    def _apply(coords: list[tuple[int, int]], universe_id: str) -> None:
        for r, c in coords:
            ri = r - pm.coordinate_convention.index_base
            ci = c - pm.coordinate_convention.index_base
            if 0 <= ri < nx and 0 <= ci < ny:
                grid[ri][ci] = universe_id

    if kind_to_universe:
        for coord_group, target_kind in [
            (pm.guide_tube_coords, "guide_tube"),
            (pm.instrument_tube_coords, "instrument_tube"),
            (pm.water_cell_coords, "water_cell"),
        ]:
            target_uv = kind_to_universe.get(target_kind, pm.default_universe_id)
            _apply(coord_group, target_uv)
    else:
        _apply(pm.guide_tube_coords, pm.default_universe_id)
        _apply(pm.instrument_tube_coords, pm.default_universe_id)
        _apply(pm.water_cell_coords, pm.default_universe_id)

    return grid


# ---------------------------------------------------------------------------
# Moderator outer universe helpers
# ---------------------------------------------------------------------------


def ensure_moderator_outer_universe(
    *,
    moderator_universe_id: str = "moderator_outer",
    coolant_material_id: str = "water",
) -> tuple[UniverseSpec, CellSpec]:
    """Create a moderator wrapper universe + cell for pin lattice outer.

    The outer universe fills the gap between the pin lattice edge and
    the assembly pitch boundary with coolant material.
    """
    cell = CellSpec(
        id=f"{moderator_universe_id}_cell",
        name="moderator outer cell",
        fill_type="material",
        fill_id=coolant_material_id,
        component_role="coolant",
        purpose="Fill assembly gap with coolant moderator",
    )
    universe = UniverseSpec(
        id=moderator_universe_id,
        name="moderator outer universe",
        cell_ids=[cell.id],
        purpose="Pin lattice outer (assembly gap fill)",
    )
    return universe, cell


# ---------------------------------------------------------------------------
# Assembly wrapper universe + cell creation
# ---------------------------------------------------------------------------


def _create_assembly_wrapper(
    type_id: str,
    pin_lattice_id: str,
    outer_moderator_universe: str,
) -> tuple[UniverseSpec, CellSpec, str]:
    """Create a real wrapper universe and cell for an assembly type.

    The wrapper cell fills with the pin lattice, and the universe groups
    it for use in the core lattice.
    """
    wrapper_cell_id = f"assembly_wrapper_cell__{type_id}"
    wrapper_universe_id = f"assembly_universe__{type_id}"

    wrapper_cell = CellSpec(
        id=wrapper_cell_id,
        name=f"wrapper cell for {type_id}",
        fill_type="lattice",
        fill_id=pin_lattice_id,
        purpose=f"Assembly wrapper for {type_id}",
    )
    wrapper_universe = UniverseSpec(
        id=wrapper_universe_id,
        name=f"assembly universe {type_id}",
        cell_ids=[wrapper_cell_id],
        purpose=f"Assembly wrapper universe for {type_id}",
    )
    return wrapper_universe, wrapper_cell, wrapper_universe_id


# ---------------------------------------------------------------------------
# Assembly templates (pin lattices + wrapper universes + specs)
# ---------------------------------------------------------------------------


def assemble_assembly_templates(
    catalog: AssemblyCatalogPatch,
    pitch_cm: float = 1.26,
    *,
    kind_to_universe: dict[str, str] | None = None,
    moderator_universe_id: str = "moderator_outer",
    coolant_material_id: str = "water",
) -> tuple[
    list[LatticeSpec],
    list[AssemblySpec],
    list[UniverseSpec],
    list[CellSpec],
    dict[str, str],
    dict[str, AssemblyTypeCountSummary],
    list[dict[str, Any]],
    UniverseSpec | None,
    CellSpec | None,
]:
    """Build per-type pin lattices, wrapper universes, and assembly specs.

    Returns
    -------
    pin_lattices, assembly_specs, wrapper_universes, wrapper_cells,
    assembly_universe_ids, count_summaries, insert_reports,
    moderator_universe, moderator_cell
    """
    issues: list[dict[str, Any]] = []
    pin_lattices: list[LatticeSpec] = []
    assembly_specs: list[AssemblySpec] = []
    wrapper_universes: list[UniverseSpec] = []
    wrapper_cells: list[CellSpec] = []
    assembly_universe_ids: dict[str, str] = {}
    summaries: dict[str, AssemblyTypeCountSummary] = {}

    mod_universe, mod_cell = ensure_moderator_outer_universe(
        moderator_universe_id=moderator_universe_id,
        coolant_material_id=coolant_material_id,
    )

    for atype in catalog.assembly_types:
        type_id = atype.assembly_type_id
        pm = atype.pin_map
        nx, ny = pm.lattice_size

        universe_pattern = _expand_assembly_pin_map(pm, kind_to_universe=kind_to_universe)

        pin_lattice_id = f"assembly_lattice__{type_id}"
        lattice = LatticeSpec(
            id=pin_lattice_id,
            name=f"pin lattice for {type_id}",
            kind="rect",
            pitch_cm=(pitch_cm, pitch_cm),
            outer_universe_id=moderator_universe_id,
            universe_pattern=universe_pattern,
            shape=(nx, ny),
            purpose=f"Base pin lattice for {type_id} (moderator outer, no localized inserts)",
        )
        pin_lattices.append(lattice)

        w_universe, w_cell, w_universe_id = _create_assembly_wrapper(
            type_id, pin_lattice_id, moderator_universe_id,
        )
        wrapper_universes.append(w_universe)
        wrapper_cells.append(w_cell)
        assembly_universe_ids[type_id] = w_universe_id

        assembly = AssemblySpec(
            id=f"assembly__{type_id}",
            name=atype.name or type_id,
            lattice_id=pin_lattice_id,
            boundary="transmission",
            purpose=f"Assembly template {type_id}",
        )
        assembly_specs.append(assembly)

        localized_counts: dict[str, int] = {}
        for intent in pm.localized_insert_intents:
            kind = intent.insert_kind
            localized_counts[kind] = localized_counts.get(kind, 0) + len(intent.coordinates)

        summary = compute_assembly_pin_counts(
            lattice_size=pm.lattice_size,
            guide_tube_coords=list(pm.guide_tube_coords),
            instrument_tube_coords=list(pm.instrument_tube_coords),
            water_cell_coords=list(pm.water_cell_coords),
            localized_insert_counts=localized_counts,
            assembly_type_id=type_id,
        )
        summaries[type_id] = summary

        localized_report = {
            "assembly_type_id": type_id,
            "insert_count": len(pm.localized_insert_intents),
            "insert_kinds": list(localized_counts.keys()),
            "in_base_lattice": False,
        }
        issues.append(localized_report)

    return (
        pin_lattices,
        assembly_specs,
        wrapper_universes,
        wrapper_cells,
        assembly_universe_ids,
        summaries,
        issues,
        mod_universe,
        mod_cell,
    )


# ---------------------------------------------------------------------------
# Core lattice construction with centered placement
# ---------------------------------------------------------------------------


def assemble_core_lattice(
    layout: CoreLayoutPatch,
    assembly_universe_ids: dict[str, str],
    *,
    outer_universe_id: str = "water",
) -> LatticeSpec:
    """Build the second-level core lattice from the core layout patch.

    Centers the lattice at origin when possible.
    """
    n_rows, n_cols = layout.shape

    universe_pattern: list[list[str]] = []
    for row in layout.assembly_pattern:
        pattern_row = [
            assembly_universe_ids.get(type_id, outer_universe_id)
            for type_id in row
        ]
        universe_pattern.append(pattern_row)

    pitch = layout.assembly_pitch_cm or 21.50

    core_width_x = n_cols * pitch
    core_width_y = n_rows * pitch

    return LatticeSpec(
        id=layout.core_lattice_id,
        name="core assembly lattice",
        kind="rect",
        pitch_cm=(pitch, pitch),
        lower_left_cm=(-core_width_x / 2.0, -core_width_y / 2.0),
        center_cm=(0.0, 0.0),
        outer_universe_id=outer_universe_id,
        universe_pattern=universe_pattern,
        shape=(n_rows, n_cols),
        purpose="Expanded from CoreLayoutPatch by hierarchical assembler (centered)",
    )


# ---------------------------------------------------------------------------
# Count summary builder
# ---------------------------------------------------------------------------


def build_core_count_summary(
    catalog: AssemblyCatalogPatch,
    layout: CoreLayoutPatch,
    type_summaries: dict[str, AssemblyTypeCountSummary],
) -> CoreCountAggregation:
    """Compute core-level aggregated counts from per-type summaries × multiplicity."""
    multiplicities: dict[str, int] = {}
    for row in layout.assembly_pattern:
        for type_id in row:
            multiplicities[type_id] = multiplicities.get(type_id, 0) + 1
    return aggregate_core_counts(type_summaries, multiplicities)


# ---------------------------------------------------------------------------
# Global axial segment compilation
# ---------------------------------------------------------------------------


@dataclass
class AxialSegment:
    """A compiled global axial segment."""

    segment_id: str
    z_min_cm: float
    z_max_cm: float
    role: str = "active"
    active_inserts: dict[str, list[str]] = field(default_factory=dict)


def compile_global_axial_segments(
    facts: FactsPatch | None,
    catalog: AssemblyCatalogPatch,
    axial_layer_boundaries: list[tuple[float, float]] | None = None,
    spacer_grid_z: list[tuple[float, float]] | None = None,
    *,
    profiles_patch: LocalizedInsertProfilesPatch | None = None,
    resolved_profiles: list[Any] | None = None,
    tolerance_cm: float = 1e-6,
) -> list[AxialSegment]:
    """Compile a global list of non-overlapping axial segments.

    Breakpoints come from:
    1. Axial domain boundaries (from facts).
    2. Shared axial layer z boundaries.
    3. Simple insert z_min/z_max (per assembly type).
    4. Resolved profile segment absolute boundaries.
    5. Spacer grid z boundaries.

    Returns sorted, non-overlapping segments with no gaps.
    """
    breakpoints: set[float] = set()

    if facts and facts.axial_domain_cm:
        breakpoints.add(facts.axial_domain_cm[0])
        breakpoints.add(facts.axial_domain_cm[1])

    if axial_layer_boundaries:
        for z_min, z_max in axial_layer_boundaries:
            breakpoints.add(z_min)
            breakpoints.add(z_max)

    for atype in catalog.assembly_types:
        for intent in atype.pin_map.localized_insert_intents:
            if intent.axial_profile_id is not None:
                continue
            if intent.z_min_cm is not None:
                breakpoints.add(intent.z_min_cm)
            if intent.z_max_cm is not None:
                breakpoints.add(intent.z_max_cm)

    if spacer_grid_z:
        for z_min, z_max in spacer_grid_z:
            breakpoints.add(z_min)
            breakpoints.add(z_max)

    if resolved_profiles:
        for rp in resolved_profiles:
            for seg in rp.resolved_segments:
                breakpoints.add(seg.absolute_z_min_cm)
                breakpoints.add(seg.absolute_z_max_cm)

    sorted_bps = sorted(breakpoints)
    if len(sorted_bps) < 2:
        return []

    segments: list[AxialSegment] = []
    for i in range(len(sorted_bps) - 1):
        z_min = sorted_bps[i]
        z_max = sorted_bps[i + 1]
        if z_max - z_min < tolerance_cm:
            continue

        seg = AxialSegment(
            segment_id=f"segment_{i}",
            z_min_cm=z_min,
            z_max_cm=z_max,
            role="active",
        )

        for atype in catalog.assembly_types:
            active_ids: list[str] = []
            for intent in atype.pin_map.localized_insert_intents:
                if intent.axial_profile_id is not None:
                    continue
                intent_zmin = intent.z_min_cm or float("-inf")
                intent_zmax = intent.z_max_cm or float("inf")
                if z_min >= intent_zmin - tolerance_cm and z_max <= intent_zmax + tolerance_cm:
                    active_ids.append(intent.insert_id)
            if active_ids:
                seg.active_inserts[atype.assembly_type_id] = active_ids

        if resolved_profiles:
            for rp in resolved_profiles:
                for rseg in rp.resolved_segments:
                    if (
                        z_min >= rseg.absolute_z_min_cm - tolerance_cm
                        and z_max <= rseg.absolute_z_max_cm + tolerance_cm
                    ):
                        type_id = rp.assembly_type_id
                        existing = seg.active_inserts.setdefault(type_id, [])
                        insert_label = f"{rp.insert_id}::{rseg.segment_id}"
                        if insert_label not in existing:
                            existing.append(insert_label)

        segments.append(seg)

    return segments


# ---------------------------------------------------------------------------
# Full hierarchical plan builder (typed result)
# ---------------------------------------------------------------------------


def build_hierarchical_core_plan(
    catalog: AssemblyCatalogPatch,
    layout: CoreLayoutPatch,
    facts: FactsPatch | None,
    *,
    pitch_cm: float = 1.26,
    kind_to_universe: dict[str, str] | None = None,
    moderator_universe_id: str = "moderator_outer",
    coolant_material_id: str = "water",
) -> HierarchicalCoreAssemblyResult:
    """Build all hierarchical core components as typed schema objects.

    Returns a :class:`HierarchicalCoreAssemblyResult` with real
    UniverseSpec, CellSpec, LatticeSpec, AssemblySpec, and CoreSpec objects.
    """
    result = HierarchicalCoreAssemblyResult()

    (
        pin_lattices,
        assembly_specs,
        wrapper_universes,
        wrapper_cells,
        assembly_universe_ids,
        summaries,
        insert_reports,
        mod_universe,
        mod_cell,
    ) = assemble_assembly_templates(
        catalog,
        pitch_cm=pitch_cm,
        kind_to_universe=kind_to_universe,
        moderator_universe_id=moderator_universe_id,
        coolant_material_id=coolant_material_id,
    )
    result.pin_lattices = pin_lattices
    result.assembly_specs = assembly_specs
    result.assembly_universes = list(wrapper_universes)
    result.assembly_wrapper_cells = list(wrapper_cells)
    result.assembly_universe_ids = assembly_universe_ids
    result.count_summaries = summaries
    result.localized_insert_reports = insert_reports

    # Add moderator universe/cell to result
    if mod_universe is not None:
        result.assembly_universes.append(mod_universe)
    if mod_cell is not None:
        result.assembly_wrapper_cells.append(mod_cell)

    outer = layout.outer_assembly_type_id or moderator_universe_id
    if layout.outer_assembly_type_id and layout.outer_assembly_type_id in assembly_universe_ids:
        outer = assembly_universe_ids[layout.outer_assembly_type_id]

    core_lattice = assemble_core_lattice(
        layout, assembly_universe_ids, outer_universe_id=outer,
    )
    result.core_lattices = [core_lattice]

    boundary = layout.boundary if layout.boundary in ("reflective", "vacuum", "periodic") else "reflective"
    core_spec = CoreSpec(
        id="core_1",
        name="hierarchical core",
        lattice_id=layout.core_lattice_id,
        assembly_ids=[a.id for a in assembly_specs],
        boundary=boundary,
        purpose="Assembled from hierarchical core patches (P2-FULLCORE-2B)",
    )
    result.core_spec = core_spec

    aggregation = build_core_count_summary(catalog, layout, summaries)
    result.core_count_aggregation = aggregation

    # Assembly gap calculation
    nx_pm, ny_pm = catalog.assembly_types[0].pin_map.lattice_size if catalog.assembly_types else (0, 0)
    pin_lattice_width = nx_pm * pitch_cm
    assembly_pitch = layout.assembly_pitch_cm or 21.50
    gap = assembly_pitch - pin_lattice_width

    result.summary = {
        "assembly_type_count": len(assembly_specs),
        "total_instances": aggregation.total_assembly_instances,
        "pin_lattice_count": len(pin_lattices),
        "wrapper_universe_count": len(wrapper_universes),
        "moderator_universe_id": moderator_universe_id,
        "core_lattice_count": len(result.core_lattices),
        "core_boundary": boundary,
        "internal_assembly_boundary": "transmission",
        "core_total_fuel": aggregation.core_total_for_role("fuel_pin"),
        "core_total_guide_tube": aggregation.core_total_for_role("guide_tube"),
        "localized_inserts_in_base_lattice": False,
        "pin_lattice_outer_is_fuel": False,
        "assembly_gap_cm": round(gap, 4),
        "assembly_half_gap_cm": round(gap / 2.0, 4),
    }

    result.ok = True
    return result
