"""Hierarchical core assembler for multi-assembly models (P2-FULLCORE-1).

This module extends the plan-builder assembler to support multi-assembly core
models by:

* Creating per-assembly-type pin lattices from an :class:`AssemblyCatalogPatch`.
* Creating per-type assembly universe/spec definitions.
* Building a second-level core lattice from a :class:`CoreLayoutPatch`.
* Aggregating per-type local counts into core-level totals.

The single-assembly backward-compatibility path (``lift_single_pin_map_to_catalog``)
converts a legacy :class:`PinMapPatch` into a single-entry catalog when needed.
"""

from __future__ import annotations

from typing import Any

from openmc_agent.plan_builder.patches import (
    AssemblyCatalogPatch,
    AssemblyPinMapPatchItem,
    AssemblyTypePatchItem,
    CoordinateConvention,
    CoreLayoutPatch,
    FactsPatch,
    LocalizedInsertIntentPatchItem,
    PinMapPatch,
)
from openmc_agent.plan_builder.scoped_counts import (
    AssemblyTypeCountSummary,
    CoreCountAggregation,
    compute_assembly_pin_counts,
    aggregate_core_counts,
)
from openmc_agent.schemas import (
    AssemblySpec,
    CoreSpec,
    LatticeSpec,
)


# ---------------------------------------------------------------------------
# Single-assembly backward compatibility
# ---------------------------------------------------------------------------


def lift_single_pin_map_to_catalog(
    pin_map: PinMapPatch,
    *,
    assembly_type_id: str = "assembly_type_1",
) -> AssemblyCatalogPatch:
    """Convert a single PinMapPatch into a single-entry AssemblyCatalogPatch.

    This preserves backward compatibility for single-assembly models that
    still use the top-level pin_map patch. The resulting catalog has exactly
    one assembly type whose pin_map mirrors the original.
    """
    pm_item = AssemblyPinMapPatchItem(
        lattice_size=pin_map.lattice_size,
        default_universe_id=pin_map.default_universe_id,
        coordinate_convention=pin_map.coordinate_convention,
        guide_tube_coords=list(pin_map.guide_tube_coords),
        instrument_tube_coords=list(pin_map.instrument_tube_coords),
        water_cell_coords=list(pin_map.water_cell_coords),
        localized_insert_intents=list(pin_map.localized_insert_intents),
        assumptions=list(pin_map.assumptions),
        source_note=pin_map.source_note,
    )
    atype = AssemblyTypePatchItem(
        assembly_type_id=assembly_type_id,
        name="auto-lifted from single pin_map",
        role="single_assembly",
        pin_map=pm_item,
    )
    return AssemblyCatalogPatch(
        assembly_types=[atype],
        assumptions=["auto_lifted_from_single_pin_map"],
        source_note="Generated by lift_single_pin_map_to_catalog",
    )


# ---------------------------------------------------------------------------
# Per-type pin lattice construction
# ---------------------------------------------------------------------------


def _expand_assembly_pin_map(
    pm: AssemblyPinMapPatchItem,
    kind_to_universe: dict[str, str] | None = None,
) -> list[list[str]]:
    """Expand a sparse assembly pin map into a full universe_pattern."""
    nx, ny = pm.lattice_size
    grid = [[pm.default_universe_id for _ in range(ny)] for _ in range(nx)]

    def _apply(coords: list[tuple[int, int]], universe_id: str) -> None:
        for r, c in coords:
            ri = r - pm.coordinate_convention.index_base
            ci = c - pm.coordinate_convention.index_base
            if 0 <= ri < nx and 0 <= ci < ny:
                grid[ri][ci] = universe_id

    _apply(pm.guide_tube_coords, pm.default_universe_id)
    _apply(pm.instrument_tube_coords, pm.default_universe_id)
    _apply(pm.water_cell_coords, pm.default_universe_id)

    if kind_to_universe:
        for coord_group, target_kind in [
            (pm.guide_tube_coords, "guide_tube"),
            (pm.instrument_tube_coords, "instrument_tube"),
            (pm.water_cell_coords, "water_cell"),
        ]:
            target_uv = kind_to_universe.get(target_kind, pm.default_universe_id)
            _apply(coord_group, target_uv)

    for intent in pm.localized_insert_intents:
        _apply(intent.coordinates, intent.insert_universe_id)

    return grid


def assemble_assembly_templates(
    catalog: AssemblyCatalogPatch,
    pitch_cm: float = 1.26,
    *,
    kind_to_universe: dict[str, str] | None = None,
) -> tuple[
    list[LatticeSpec],
    list[AssemblySpec],
    dict[str, AssemblyTypeCountSummary],
    list[str],
]:
    """Build per-type pin lattices and assembly specs from the catalog.

    Returns
    -------
    lattices : list[LatticeSpec]
        One pin lattice per assembly type.
    assemblies : list[AssemblySpec]
        One assembly spec per assembly type.
    count_summaries : dict[str, AssemblyTypeCountSummary]
        Local pin counts per assembly type.
    issues : list[str]
        Non-fatal assembly warnings.
    """
    issues: list[str] = []
    lattices: list[LatticeSpec] = []
    assemblies: list[AssemblySpec] = []
    summaries: dict[str, AssemblyTypeCountSummary] = {}

    for atype in catalog.assembly_types:
        type_id = atype.assembly_type_id
        pm = atype.pin_map
        nx, ny = pm.lattice_size

        universe_pattern = _expand_assembly_pin_map(pm, kind_to_universe=kind_to_universe)

        lattice_id = f"assembly_lattice__{type_id}"
        lattice = LatticeSpec(
            id=lattice_id,
            name=f"pin lattice for {type_id}",
            kind="rect",
            pitch_cm=(pitch_cm, pitch_cm),
            outer_universe_id=pm.default_universe_id,
            universe_pattern=universe_pattern,
            shape=(nx, ny),
            purpose=f"Expanded from AssemblyCatalogPatch type {type_id}",
        )
        lattices.append(lattice)

        assembly = AssemblySpec(
            id=f"assembly__{type_id}",
            name=atype.name or type_id,
            lattice_id=lattice_id,
            boundary="reflective",
            purpose=f"Assembly template {type_id}",
        )
        assemblies.append(assembly)

        localized_counts: dict[str, int] = {}
        for intent in pm.localized_insert_intents:
            kind = intent.insert_kind
            localized_counts[kind] = localized_counts.get(kind, 0) + len(intent.coordinates)

        summary = compute_assembly_pin_counts(
            lattice_size=pm.lattice_size,
            guide_tube_coords=list(pm.guide_tube_coords),
            instrument_tube_coords=list(pm.instrument_tube_coords),
            water_cell_coords=list(pm.water_cell_coords),
            localized_insert_counts=localized_counts,
            assembly_type_id=type_id,
        )
        summaries[type_id] = summary

    return lattices, assemblies, summaries, issues


# ---------------------------------------------------------------------------
# Core lattice construction
# ---------------------------------------------------------------------------


def assemble_core_lattice(
    layout: CoreLayoutPatch,
    assembly_universe_ids: dict[str, str],
    *,
    outer_universe_id: str = "water",
) -> LatticeSpec:
    """Build the second-level core lattice from the core layout patch.

    Parameters
    ----------
    layout : CoreLayoutPatch
        The core layout with assembly_pattern referencing assembly type IDs.
    assembly_universe_ids : dict[str, str]
        Maps assembly_type_id → fill universe_id for each assembly template.
    outer_universe_id : str
        Universe to fill positions outside the pattern (reflector/water).
    """
    n_rows, n_cols = layout.shape

    universe_pattern: list[list[str]] = []
    for row in layout.assembly_pattern:
        pattern_row = [
            assembly_universe_ids.get(type_id, outer_universe_id)
            for type_id in row
        ]
        universe_pattern.append(pattern_row)

    pitch = layout.assembly_pitch_cm or 21.50

    return LatticeSpec(
        id=layout.core_lattice_id,
        name="core assembly lattice",
        kind="rect",
        pitch_cm=(pitch, pitch),
        outer_universe_id=outer_universe_id,
        universe_pattern=universe_pattern,
        shape=(n_rows, n_cols),
        purpose="Expanded from CoreLayoutPatch by hierarchical assembler",
    )


# ---------------------------------------------------------------------------
# Count summary builder
# ---------------------------------------------------------------------------


def build_core_count_summary(
    catalog: AssemblyCatalogPatch,
    layout: CoreLayoutPatch,
    type_summaries: dict[str, AssemblyTypeCountSummary],
) -> CoreCountAggregation:
    """Compute core-level aggregated counts from per-type summaries × multiplicity.

    Multiplicities are derived from the layout's assembly_pattern.
    """
    multiplicities: dict[str, int] = {}
    for row in layout.assembly_pattern:
        for type_id in row:
            multiplicities[type_id] = multiplicities.get(type_id, 0) + 1

    return aggregate_core_counts(type_summaries, multiplicities)


# ---------------------------------------------------------------------------
# Full hierarchical plan builder
# ---------------------------------------------------------------------------


def build_hierarchical_core_plan(
    catalog: AssemblyCatalogPatch,
    layout: CoreLayoutPatch,
    facts: FactsPatch | None,
    *,
    pitch_cm: float = 1.26,
    assembly_universe_ids: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Build all hierarchical core components.

    Returns a dict with keys:
        pin_lattices, assemblies, core_lattice, core_spec,
        count_summaries, core_count_aggregation, issues
    """
    issues: list[str] = []

    pin_lattices, assemblies, summaries, asm_issues = assemble_assembly_templates(
        catalog, pitch_cm=pitch_cm,
    )
    issues.extend(asm_issues)

    if assembly_universe_ids is None:
        assembly_universe_ids = {}
        for atype in catalog.assembly_types:
            assembly_universe_ids[atype.assembly_type_id] = f"assembly_universe__{atype.assembly_type_id}"

    outer = layout.outer_assembly_type_id or "water"
    if layout.outer_assembly_type_id and layout.outer_assembly_type_id in assembly_universe_ids:
        outer = assembly_universe_ids[layout.outer_assembly_type_id]

    core_lattice = assemble_core_lattice(layout, assembly_universe_ids, outer_universe_id=outer)

    core_spec = CoreSpec(
        id="core_1",
        name="hierarchical core",
        lattice_id=layout.core_lattice_id,
        assembly_ids=[a.id for a in assemblies],
        boundary=layout.boundary,
        purpose="Assembled from hierarchical core patches",
    )

    aggregation = build_core_count_summary(catalog, layout, summaries)

    return {
        "pin_lattices": pin_lattices,
        "assemblies": assemblies,
        "core_lattice": core_lattice,
        "core_spec": core_spec,
        "count_summaries": summaries,
        "core_count_aggregation": aggregation,
        "assembly_universe_ids": assembly_universe_ids,
        "issues": issues,
    }
